### ISSUE TITLE
Search results not narrowing as I type

### ISSUE THREAD

**Issue by umyeah** [vdepizzol/jquery-tokeninput#12]
As I type the tag name, the full list of tags is returned every time. I am using a server for the json. They are all of the form {id,name} so I am assuming that the default search of name should work correctly.

I ended up using the code below to narrow the results. Should something like this be happening by default?

``` javascript
onResult:function(results){
     return $.grep(results,function(value,index){
          return (value.name).indexOf($('.token-input-input-token-facebook input').val())!=-1
     });
}
```

**Comment by vdepizzol** [comment]
Hey, @umyeah.
jquery-tokeninput relies on server filtering when reading the results. Basically it sends a "q" variable trough GET (this can be changed in settings) to server with what the user typed as value every time it is requesting something, so the server-side code have to do its own search and only return the matched items.

This happens because returning all the results in one row would require too much traffic for most of the situations.

However, if you have only a small number of items and want to preload all of them, you can inform an object instead of an url, and an internal js local search would do its job as you'd like.

Per instance:

<pre><code>$("#demo-input-local").tokenInput([
    {id: 7, name: "Ruby"},
    {id: 11, name: "Python"},
    {id: 13, name: "JavaScript"},
    {id: 17, name: "ActionScript"}
]);</code></pre>

**Comment by umyeah** [comment]
Aah OK. I had a feeling I was misunderstanding that part of the search. Thanks for clearing this up so quickly.
